import assert from 'node:assert/strict';
import prisma, { pool } from '../src/config/prisma';
import { weeklyRange } from '../src/services/weeklyWorkOrderMetrics';
import { freezeWeeklyPlan, saveWeeklyCut, getWeeklyReport } from '../src/services/weeklyWorkOrderService';
import { requirePermission, requireWritable } from '../src/middlewares/authMiddleware';
import { weeklyReport } from '../src/controllers/weeklyWorkOrderController';

const date = (value: string) => new Date(value);
const monday = date('2026-09-21T06:00:00Z');
const tuesday = date('2026-09-22T18:00:00Z');
const wednesday = date('2026-09-23T18:00:00Z');
const week = '2026-09-21';
async function main() {
  assert.match(new URL(process.env.DATABASE_URL!).pathname, /^\/fiix_cmms_test_weekly_[a-f0-9]+$/);
  assert.equal(weeklyRange('2026-09-27').key, week, 'Domingo pertenece a la semana anterior');
  assert.equal(weeklyRange('2026-09-28').key, '2026-09-28');
  assert.equal(weeklyRange('2027-01-01').key, '2026-12-28');
  assert.equal(weeklyRange(week).start.toISOString(), '2026-09-21T06:00:00.000Z');
  assert.throws(() => weeklyRange('2026-02-30'));
  const user = await prisma.user.create({ data: { name: 'Prueba semanal', email: 'weekly@test.local', password_hash: 'x', role: 'ADMINISTRADOR' } });
  const zoneA = await prisma.zone.create({ data: { name: 'Zona A' } });
  const zoneB = await prisma.zone.create({ data: { name: 'Zona B' } });
  const asset = await prisma.asset.create({ data: { name: 'Equipo', internal_code: 'WEEKLY-TEST', brand: 'X', model: 'X', status: 'OPERATIVO' } });
  const make = (title: string, zone = zoneA.id, extra: Record<string, unknown> = {}) => prisma.workOrder.create({ data: {
    title, status: 'PENDIENTE', asset_id: asset.id, zone_id: zone, created_by_id: user.id,
    created_at: date('2026-09-20T18:00:00Z'), scheduled_date: monday, due_date: date('2026-09-22T17:00:00Z'), ...extra,
  } });
  const a = await make('Programa A');
  const b = await make('Programa B', zoneB.id);
  const noDue = await make('Sin límite', zoneA.id, { due_date: null });
  const sunday = await make('Domingo', zoneA.id, { due_date: date('2026-09-28T05:59:59Z') });
  await make('Lunes siguiente', zoneA.id, { due_date: date('2026-09-28T06:00:00Z') });
  await make('Cerrada antes de semana', zoneA.id, { status: 'FINALIZADO', completed_at: date('2026-09-20T18:00:00Z') });
  const plans = await Promise.all([freezeWeeklyPlan(week, user.id, monday), freezeWeeklyPlan(week, null, monday)]);
  assert.equal(plans[0].week_start, plans[1].week_start);
  assert.equal(await prisma.weeklyWorkOrderPlan.count(), 1);
  let report = await getWeeklyReport(week, [], undefined, monday);
  assert.equal(report.counts.program, 4);
  assert.equal(report.plan?.lateStart, false);
  assert.equal(report.compliance, 0);
  assert.equal(report.daily[1]!.cumulative, null, 'Días futuros no muestran ceros');
  await prisma.workOrder.update({ where: { id: a.id }, data: { status: 'FINALIZADO', completed_at: date('2026-09-22T16:00:00Z') } });
  await prisma.workOrder.update({ where: { id: b.id }, data: { status: 'EN_ESPERA', hold_reason: 'Falta refacción' } });
  const extra = await make('Trabajo nuevo', zoneB.id, { created_at: tuesday });
  const cut = await saveWeeklyCut(week, user.id, 'MANUAL', tuesday);
  report = await getWeeklyReport(week, [], cut.id, wednesday);
  assert.equal(report.counts.program, 4);
  assert.equal(report.counts.completed, 1);
  assert.equal(report.counts.paused, 1);
  assert.equal(report.counts.overdue, 1, 'Sin límite y programada a domingo aún no están vencidas');
  assert.equal(report.compliance, 25);
  assert.equal(report.counts.incoming, 1);
  assert.equal(report.counts.additions, 1);
  assert.equal(report.daily[0]!.closed, null, 'No inventar corte del lunes');
  assert.equal(report.daily[1]!.closed, 1);
  assert.equal(report.daily[2]!.closed, null, 'Al consultar martes no revelar miércoles');
  const filtered = await getWeeklyReport(week, [zoneA.id], cut.id, wednesday);
  assert.equal(filtered.counts.program, 3);
  assert.equal(filtered.counts.paused, 0);
  const multi = await getWeeklyReport(week, [zoneA.id, zoneB.id], cut.id, wednesday);
  assert.equal(multi.counts.program, 4);
  await prisma.workOrder.update({ where: { id: b.id }, data: { status: 'FINALIZADO', completed_at: wednesday, due_date: date('2026-09-29T18:00:00Z'), zone_id: zoneA.id } });
  await prisma.workOrder.update({ where: { id: noDue.id }, data: { status: 'ANULADO' } });
  await prisma.workOrder.delete({ where: { id: sunday.id } });
  report = await getWeeklyReport(week, [], undefined, wednesday);
  assert.equal(report.counts.program, 4, 'Anulada, reprogramada y eliminada no cambian el denominador');
  assert.equal(report.counts.cancelled, 1);
  assert.equal(report.counts.deleted, 1);
  assert.equal(report.counts.rescheduled, 1);
  assert.equal(report.compliance, 50);
  const moved = await getWeeklyReport(week, [zoneB.id], undefined, wednesday);
  assert.equal(moved.counts.program, 1, 'La zona inicial conserva su compromiso');
  assert.equal(moved.counts.completed, 1);
  const old = await getWeeklyReport(week, [], cut.id, wednesday);
  assert.equal(old.counts.paused, 1, 'Corte previo inmutable');
  assert.equal(old.counts.deleted, 0);
  assert.equal(old.counts.cancelled, 0);
  const autos = await Promise.all([saveWeeklyCut(week, null, 'AUTO', wednesday), saveWeeklyCut(week, null, 'AUTO', wednesday)]);
  assert.equal(autos[0].id, autos[1].id, 'Cron idempotente entre procesos');
  const past = await getWeeklyReport(week, [], undefined, date('2026-10-01T18:00:00Z'));
  assert.equal(past.selectedCutId, autos[0].id);
  const missing = await getWeeklyReport('2026-09-14', [], undefined, wednesday);
  assert.equal(missing.hasData, false);
  await assert.rejects(saveWeeklyCut('2026-09-14', user.id, 'MANUAL', wednesday));
  await assert.rejects(freezeWeeklyPlan('2026-09-28', user.id, wednesday));
  await assert.rejects(getWeeklyReport('2026-09-14', [], cut.id, wednesday));
  await freezeWeeklyPlan('2026-09-28', user.id, date('2026-09-30T18:00:00Z'));
  assert.equal((await getWeeklyReport('2026-09-28', [], undefined, date('2026-09-30T18:00:00Z'))).plan?.lateStart, true);
  let status = 0; let next = false;
  const res: any = { status: (s: number) => { status = s; return res; }, json: () => {} };
  requireWritable({ user: { userId: user.id, role: 'OBSERVADOR' } } as any, res, () => { next = true; });
  assert.equal(status, 403); assert.equal(next, false);
  await requirePermission('VIEW_ALL_WORK_ORDERS')({ user: { userId: user.id, role: 'TECNICO' } } as any, res, () => { next = true; });
  assert.equal(status, 403); assert.equal(next, false);
  await weeklyReport({ query: { week: 'not-a-date' } } as any, res);
  assert.equal(status, 400);
  assert.ok(extra.id);
  console.log('OK: semana México lun-dom, límites/año, programa fijo, concurrencia, zonas, cierres, pausas, vencidas, altas, anuladas, eliminadas, reprogramaciones, cortes inmutables, históricos ausentes y permisos.');
}
main().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { await prisma.$disconnect(); await pool.end(); });
